DB_CORE_HOST?=localhost
DB_CORE_NAME?=etu
DB_CORE_USER?=postgres
DB_CORE_PASSWORD?=password
DB_CORE_PORT?=5432

DOWN_LIMIT?=1

up:
	@DB_CORE_HOST=${DB_CORE_HOST} \
	DB_CORE_NAME=${DB_CORE_NAME} \
	DB_CORE_USER=${DB_CORE_USER} \
	DB_CORE_PORT=${DB_CORE_PORT} \
	DB_CORE_PASSWORD=${DB_CORE_PASSWORD} \
		sql-migrate up -env=main

down:
	@DB_CORE_HOST=${DB_CORE_HOST} \
	DB_CORE_NAME=${DB_CORE_NAME} \
	DB_CORE_USER=${DB_CORE_USER} \
	DB_CORE_PORT=${DB_CORE_PORT} \
	DB_CORE_PASSWORD=${DB_CORE_PASSWORD} \
		sql-migrate down -env=main -limit=${DOWN_LIMIT}

status:
	@DB_CORE_HOST=${DB_CORE_HOST} \
	DB_CORE_NAME=${DB_CORE_NAME} \
	DB_CORE_USER=${DB_CORE_USER} \
	DB_CORE_PORT=${DB_CORE_PORT} \
	DB_CORE_PASSWORD=${DB_CORE_PASSWORD} \
		sql-migrate status -env=main
